### PR TITLE
Updated getInitialProps to getServerSideProps

### PR DESCRIPTION
**Pull request by shaswatsaxena**
- Updated dependencies
- With nextjs 9.3 getInitialProps has been replaced by getServerSideProps.
- Prismic logo image path fixed

### CODE REVIEW

**Comment by osamaaamer95** [comment]
Shouldn't this use `getStaticProps`? Rationale [here](https://nextjs.org/docs/basic-features/data-fetching#when-should-i-use-getstaticprops).

**Comment by hypervillain** [comment]
You're right @osamaaamer95, `getStaticProps` makes more sense here.
Want to take care of it?

**Comment by osamaaamer95** [comment]
@shaswatsaxena how about it?

**Comment by shaswatsaxena** [comment]
@osamaaamer95 Sure, go ahead. I couldn't get the current previews setup to work with `getStaticProps`.

**Comment by hypervillain** [comment]
I think this ressource could be of great help in your situation:
https://nextjs.org/docs/advanced-features/preview-mode

See in particular the "Fetch preview data" section, where the preview logic would be specific to Prismic. I'll take a look in the coming days but feel free to experiment 👍

**Comment by hypervillain** [comment]
I found a working example in the Next.js examples folder: https://github.com/zeit/next.js/tree/canary/examples/cms-prismic

It shouldn't be too hard to add the api routes

**Comment by hypervillain** [comment]
Hey again 👋
I made the new `getStaticProps` work with Prismic but it clashes a bit with the Toolbar. I'm trying to understand what can be done there but will push something in the meantime. Thank you for your patience 😊

**Pull request closed without merging**
